### ISSUE TITLE
Undefined offset

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#40]
Notice: Undefined offset: 1 in list($lastname, $firstname)

Works in some cases, some cases not. Why are there different combinations of name formatting? "John Doe" or "Doe John" or "Doe, John" in customerIdentity->fullName?

```php
            if (!empty($response->customerIdentity->fullName)) {
              list($lastname, $firstname) = explode(',', (string)$response->customerIdentity->fullName);
              $order->data['customer']['shipping_address']['firstname'] = trim($firstname);
              $order->data['customer']['shipping_address']['lastname']  = trim($lastname);
            }
```

**Comment by kilskrift** [comment]
Added to documentation 6.3 GetAddresses along with more information on the GetAddressResponse contents.

**Comment by timint** [comment]
1. So what became the solution here? Our e-commerce platform has two fields: firstname and lastname. And from my understanding it's impossible to get one of the two from SveaWebPay.

2. Despite the two fields, getAddress an individual in Finland does not return firstName and lastName even though documenation says they are only skipped in CreateOrderResponse.

3. Why are the two fields skipped in CreateOrderResponse?

**Comment by kilskrift** [comment]
A possible solution (for individual customers in SE and DK only, though) to the need of having well-defined firstname and lastname fields is to get them via a getAddresses request. As the createOrder request is based on the same customer credentials (SE: personnummer) as the getAddresses request, the firstname and lastname from getAddresses is also valid for the address returned with the createOrder response. 

This is for individual customers though, for company customers the result may vary depending an addressSelector field was supplied with the createOrder request.

For other countries, you must rely on the amalgated fullName field.

The reason firstName and lastName is not returned with the createOrder response is due to those fields not being returned by the underlying webservice, and they are thus unavailable.

/kgm
