### ISSUE TITLE
Decimal missing in recurring transaction.

### ISSUE THREAD

**Issue by keviny86** [sveawebpay/php-integration#55]
There is no decimal when doing a recurring transaction.
When i try to charge 12.5 i get back the amount 1250 in the RecurTransactionResponse Object.

**Comment by kilskrift** [comment]
This is normal and due to how the underlying systems represent payments, see the response class documentation: [RecurTransactionResponse](http://sveawebpay.github.io/php-integration/api/classes/Svea.HostedService.RecurTransactionResponse.html#property_amount), and, perhaps better worded, also [HostedPaymentResponse](http://sveawebpay.github.io/php-integration/api/classes/Svea.HostedService.HostedPaymentResponse.html#property_amount).

/kgm

**Comment by keviny86** [comment]
In HostedPaymentResponse i get back amount with decimal, is this normal behavior?

**Comment by kilskrift** [comment]
Thank you for your remark, I stand corrected.

Actually, it seems that we changed how the amount is presented for hosted payments
when moving the response into a dedicated HostedPaymentResponse class.

This was done so that as of 2.0 of the package, the response amount is shown in the same way for hosted and synchronous payment methods (see CreateOrderResponse). The response amount should be presented as a decimal number in both cases.
 
I'll update the attribute documentation in HostedTransactionResponse, and add a decimal representation "decimalamount" of the amount to the RecurTransactionResponse class. 

The fix will be available in release 2.2.11.

/kgm
