### ISSUE TITLE
Recurring card payment with "free month"

### ISSUE THREAD

**Issue by keviny86** [sveawebpay/php-integration#57]
Hello,

I want to give a users a "free month" when ordering a recurring product and i need the user to complete the card payment so i can get a subscription id, but it seams that i cant redirect user to card payment form if the charge price is zero.

**Comment by TXC** [comment]
What if you set the full amount and add a discount?

**Comment by kilskrift** [comment]
Hi, 

thanks for your question, and sorry about the late reply. 

The way to set up a recurring subscription without actually charging a customer is like this:

You will need to to specify a small order amount (i.e. SEK 1) for the initial subscription request. Then make sure to specify RECURRING instead of RECURRINGCAPTURE when setting the order subscription type:

->setSubscriptionType(Svea\HostedService\HostedPayment::RECURRINGCAPTURE);

This will result in the (small) amount being reserved in the customer account, but as the card order will not be captured, the reserved amount will be released back to the customer in about a week's time, and you will receive the subscription id with the create order result in the ususal manner.

I'll make sure to update the documentation, thanks again for the report.

/kgm
