### ISSUE TITLE
listPaymentMethods is using card-details

### ISSUE THREAD

**Issue by TXC** [sveawebpay/php-integration#61]
How can i use listpaymentmethod without card-details?

Since it seems that this method is using MerchantId that is used in banking/card-payments

**Comment by nlii** [comment]
This method is used to get a list of your configured paymentmethod at the Svea PSP. A way to use this is if you want to list your bankmethods in the checkout to enable for the customer to choose payment whithout going to the PayPage. 
For this you need a config object with your merchantId and secret
If you don't yet have an account at Svea you can use the default Config in the SveaConfig.php.

Because Invoice and PaymentPlan have a country specific account conected with each clientId you do not need to query this.
