### ISSUE TITLE
There is an error in XML document (2, 210).

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#70]
**Warning: Server was unable to read request. ---> There is an error in XML document (2, 210). ---> Input string was not in a correct format.**

The error was returned from the GetAddress component for a danish visitor.

Preferably return an error instead like "The given country code is not supported for this operation".

**Comment by nlii** [comment]
Yes, this indicates that something is wrong with the request so the system can not read it. If you call prepareRequest() instead of doRequest() in the php-integration library, it will return the request object before calling the SoapClient. 
If you contact our customer service they can use that to help you find what is wrong.
