### ISSUE TITLE
deliverCardOrderRows doesn't considerate row quantity

### ISSUE THREAD

**Issue by christiankarlsson** [sveawebpay/php-integration#75]
https://github.com/sveawebpay/php-integration/blob/master/src/BuildOrder/DeliverOrderRowsBuilder.php#L243

**Comment by fre-sund** [comment]
Hi,

As it isn't possible to deliver card orderrows several times due to how card transactions work, the method will probably be removed or refactored in the future.

The method now "confirms" the total amount of the orderrows that are passed through the DeliverOrderRows object for the acquiring process by calculating the total amount of all orderrows then subtracting it with the total amount of the orderrows that are actually going to be deducted from the debit/credit card.
Then it takes that amount and passes it into another method called LowerTransaction which removes that amount from the original transaction in our payment gateway.

The orderrows are not sent anywhere but to our payment gateway and is just kept for our customers to see. Our external partner that handles the acquiring process does not want/need any orderrows, they just want the amount of the transaction that should be debited from the purchaser's card.

I took a brief overview of the package and found that it isn't possible on any other payment method either (I could be wrong though), but it is possible to add your own logic if you want to do it on other payment methods.

For example if you want to deliver a certain quantity on a single order row with an invoice you can first update the orderrow to remove the specified quantity then add a new orderrow with the specifed quantity then deliver it.

Hope this answer helps you.

Kind regards,
Fredrik
