### ISSUE TITLE
How to query the order when using checkout orders

### ISSUE THREAD

**Issue by watta90** [sveawebpay/php-integration#85]
Hi,

I create a checkout order  and place the GUI iFrame for the user to complete it, I store the OrderId in my db when the order is created. Later on I like to query the order but depending on what the user chose in the iFrame I need to call a different method. 

If the user payed with card, invoice or bank transfer I need to use

```
WebPayAdmin::queryOrder($config)->setCheckoutOrderId($OrderId)
//or
WebPayAdmin::queryOrder($config)->setOrderId($OrderId)
//or
WebPayAdmin::queryOrder($config)->setTransactionId($OrderId)

//Then obviously call their corresponding query method
```

Is there any better way to use the checkout iframe?

**Comment by fre-sund** [comment]
Hi,

You don't need to call a different method, you can set the checkoutOrderId and call that method regardless of the payment method as long as the payment was finalized using Svea Checkout rather than one of the standalone payment methods.

See an example here: https://github.com/sveawebpay/php-integration/blob/master/example/checkout/getCheckoutOrder.php

Br,
fre-sund

**Comment by watta90** [comment]
@fre-sund any news on this? I have a deadline really soon and need to know if I should do any workaround or not. 

Thanks in advance :)

**Comment by fre-sund** [comment]
Sorry for my late reply, I'm sick right now (not corona btw :) ) which is why I haven't responded. If the payment method is null it means that Payment Admins API(which is the one you're querying) hasn't been updated yet, Payment Admin collects information from other internal systems and all order updates gets queued, which sometimes takes longer than a second. If you want to know the payment method instantly you can call the method in this example instead: https://github.com/sveawebpay/php-integration/blob/master/example/checkout/getCheckoutOrder.php

The reason that bank transfers get set to delivered instantly is because that the transaction is settled immediately, which is unique for the directbank transfer payment methods. Other payment methods are set to "Open" until they are delivered.

**Comment by watta90** [comment]
> If the payment method is null it means that Payment Admins API(which is the one you're querying) hasn't been updated yet, Payment Admin collects information from other internal systems and all order updates gets queued, which sometimes takes longer than a second. If you want to know the payment method instantly you can call the method in this example instead: https://github.com/sveawebpay/php-integration/blob/master/example/checkout/getCheckoutOrder.php

Ah thanks for that! This solved both my issues; `PaymentMethod=null` and `Order not found` issue I created here #86 

Hope you get well soon :)
